A program for printing the sub sequences of a given string using recursion
hash-define-organization/Hacktober-Fest-2021 pull request #100
Opened 2021-10-02 07:18 UTC by itsnitish22

Used recursion to print all the sub sequences of a given string.

2021-10-02 09:18 UTC, achitJ requested changes

2021-10-02 09:18 UTC, achitJ commented on DSA/Cpp/Recursion_and_Backtracking/TowerOfHanoi.cpp
> +}
Do not add a code that you didn't mention in the issue or the PR in the first place.

2021-10-02 09:31 UTC, itsnitish22 commented
Raised the issue. Now you can go through the code and suggest any changes if required.

2021-10-02 12:31 UTC, achitJ approved these changes
LGTM

2021-10-03 06:16 UTC, itsnitish22 commented
Any updates?

2021-10-03 13:34 UTC, Bhavye-Malhotra commented
Lgtm too

2021-10-03 13:35 UTC, merged

2021-10-03 14:10 UTC, itsnitish22 commented
Just saw that your repository got excluded for hacktoberfest. Why is it so?