added 2-D Matrix Spiral Problem
hash-define-organization/Hacktober-Fest-2021 pull request #39
Opened 2021-10-01 14:23 UTC by HarshalRathore

closes #35 
Signed-off-by: Harshal <harshalrathore2014@gmail.com>

2021-10-01 15:40 UTC, WINOFFRG requested changes
You should use proper naming, Prevent the use of variables like `i, j, k, m, n`
Give proper naming.

2021-10-01 17:34 UTC, HarshalRathore commented
@WINOFFRG I have changed n->rows and m->column.
But I will leave i & j as they are because they are temporary variables they do not have scope in the entire program

2021-10-02 06:46 UTC, HarshalRathore commented
@DhairyaBahl @Bhavye-Malhotra
I request you to please review the changes requested by @WINOFFRG and merge this PR to `master` as soon as possible. Because if this PR is still open I won't be able to create any more PRs

2021-10-02 06:48 UTC, Bhavye-Malhotra approved these changes

2021-10-02 08:24 UTC, VaibhavPaliwal0007 approved these changes

2021-10-02 08:24 UTC, merged